#     Self Service Portal - A Portal for users to request services and have them automagically provisioned
#     Copyright (C) 2024  Eric C Moody
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"
servers:
  - url: "/api"

components:
  schemas:
    Runner_result:
      type: "object"
      required:
        - job_id
        - pod_id
        - execution_status
        - execution_output
      properties:
        job_id:
          type: "string"
        pod_id:
          type: "string"
        execution_status:
          type: "string"
        execution_output:
          type: "string"
  parameters:
    job_id:
      name: "job_id"
      description: "The ID of the job that submitted the runner"
      in: path
      required: True
      schema:
        type: "string"
paths:
  /runner/{job_id}:
    post:
      operationId: "runner.result"
      tags:
        - "Runner"
      summary: "Captures the result of the runner responce"
      parameters:
        - $ref: "#/components/parameters/job_id"
      requestBody:
        description: "The result of the runner execution"
        required: true
        content:
          application/json:
            schema:
              x-body-name: "runner_result"
              $ref: "#/components/schemas/Runner_result"
      responses:
        "200":
          description: "Successfully captured the result"